SELECT COUNT(0) FROM INDICADORES_RDNG WHERE QTDE_CCRC = '1' AND DATA_IMPORTACAO = '28/03/2023'
SELECT COUNT(0) FROM INDICADORES_RDNG WHERE QTDE_CCRC <> '1' AND DATA_IMPORTACAO = '28/03/2023'

SELECT count(0) FROM INDICADORES_RDNG where QTDE_NAO_RASTREADO is null


SELECT DATA_IMPORTACAO , COUNT(0) AS 'SO_CHECK_COMBO_SEM_LINK'
FROM   INDICADORES_RDNG 
WHERE  QTDE_NAO_RASTREADO = '1'
GROUP BY DATA_IMPORTACAO
ORDER BY DATA_IMPORTACAO


SELECT DATA_IMPORTACAO , COUNT(0) AS 'INDICADOR_CAMINHO_CC_VALIDO'
FROM   INDICADORES_RDNG 
WHERE  INDICADOR_CAMINHO_CC_VALIDO = '1'
GROUP BY DATA_IMPORTACAO
ORDER BY DATA_IMPORTACAO

SELECT DATA_IMPORTACAO , COUNT(0) AS 'INDICADOR_JUSTIFICATIVA'
FROM   INDICADORES_RDNG 
WHERE  INDICADOR_JUSTIFICATIVA = '1'
GROUP BY DATA_IMPORTACAO
ORDER BY DATA_IMPORTACAO



UPDATE INDICADORES_RDNG SET DATA_IMPORTACAO = '28/03/2023' WHERE DATA_IMPORTACAO = '29/03/2023'

SELECT INCLUSAO_REQ_CLEARCASE FROM INDICADORES_RDNG WHERE INCLUSAO_REQ_CLEARCASE <> '' and INCLUSAO_REQ_CLEARCASE <> 'None'


SELECT count(0) FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023'

SELECT count(0) FROM INDICADORES_RDNG WHERE QTDE_RASTREADO = '1' AND DATA_IMPORTACAO = '27/03/2023'
SELECT count(0) FROM INDICADORES_RDNG WHERE QTDE_NAO_RASTREADO = '1' AND DATA_IMPORTACAO = '27/03/2023'


SELECT * FROM INDICADORES_RDNG WHERE QTDE_RASTREADO = '1' AND DATA_IMPORTACAO = '28/03/2023'
AND HU IN ( SELECT HU FROM INDICADORES_RDNG WHERE QTDE_RASTREADO <> '1' AND QTDE_NAO_RASTREADO <> '1')
AND DATA_IMPORTACAO = '27/03/2023'



SELECT INCLUSAO_REQ_CLEARCASE FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023' AND INCLUSAO_REQ_CLEARCASE like '%MIGRA%' AND INCLUSAO_REQ_CLEARCASE not like '%01-REQ%'
SELECT INCLUSAO_REQ_CLEARCASE FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023' AND INCLUSAO_REQ_CLEARCASE like '%01-REQ%' AND HU NOT IN (SELECT HU FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023' AND INCLUSAO_REQ_CLEARCASE like '%MIGRA%')

SELECT INCLUSAO_REQ_CLEARCASE FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023' AND (INCLUSAO_REQ_CLEARCASE like '%MIGRA%' OR INCLUSAO_REQ_CLEARCASE like '%01-REQ%')



SELECT * FROM INDICADORES_RDNG WHERE DATA_IMPORTACAO = '28/03/2023' AND INCLUSAO_REQ_CLEARCASE like '%MIGRA%' AND INCLUSAO_REQ_CLEARCASE not like '%01-REQ%'





SELECT count(DISTINCT(HU)) FROM INDICADORES_RDNG WHERE QTDE_RASTREADO = '1' AND DATA_IMPORTACAO = '29/03/2023'

SELECT count(DISTINCT(HU)) FROM INDICADORES_RDNG WHERE QTDE_NAO_RASTREADO <> '1' AND QTDE_RASTREADO <> '1' AND DATA_IMPORTACAO = '29/03/2023'