FROM python:3.10.4

#ENV VIRTUAL_ENV=/env_Clearcase
#RUN python3 -m venv $VIRTUAL_ENV
#ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
RUN pip freeze >> requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt
#RUN pip install flask

#RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# Run the application:
COPY Clearcase.db .
COPY BancodeDados.py .
COPY servidor.py .

CMD ["python", "servidor.py"]