SELECT   DISTINCT(GC) AS GERENTE , COMUNIDADE
FROM     VOB_GC_COMUNIDADE
GROUP BY GERENTE , COMUNIDADE
ORDER BY COMUNIDADE ASC


SELECT * FROM VOB_GC_COMUNIDADE WHERE GC = 'C021613'

SELECT VOB , SERVIDOR , COMUNIDADE , FABRICA FROM VOBS


SELECT * FROM VOBs WHERE CAMINHO_COMPART IS NULL

SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART LIKE '%FOTON%' ORDER BY GRUPO_COMPART

SELECT * FROM COMPARTILHAMENTOS WHERE NOME_COMPART = "SIATV"
SELECT * FROM VOBS WHERE VOB like '%SIGCB%'






SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%ARRECADACAO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CANAIS_CLIENTE%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CANAIS_INTERNO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CAMBIO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CONTRATACOES%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CONTROLADORIA%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CRM_CADASTRO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%CREDITO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%DADOS%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%DEPOSITO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%ESTRUTURANTES_TI%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%FINANCEIRO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%FOMENTO_DJ%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%FUNDOS_GOVERNO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%HABITACAO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%INSTITUCIONAL%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%LOTERIAS%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%MEIOS_PAGAMENTO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%OPEN_BANKING%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%OPERACOES_BANCARIAS%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%PESSOAS%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%PROGRAMAS_SOCIAIS%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%RISCO%'
SELECT DISTINCT(GRUPO_COMPART) FROM COMPARTILHAMENTOS WHERE GRUPO_COMPART like '%SEGURANCA%'
